FROM oven/bun:alpine

RUN apk add --no-cache libc6-compat libstdc++

RUN adduser -D -s /bin/sh -u 1001 nestjsuser

WORKDIR /backend.nestjs

RUN chown nestjsuser:nestjsuser /backend.nestjs

USER nestjsuser

COPY --chown=nestjsuser:nestjsuser package.json bun.lock* ./

# Устанавливаем зависимости
RUN bun install

# Копируем остальной исходный код
COPY --chown=nestjsuser:nestjsuser . .

# Открываем порт (по умолчанию NestJS использует 3000)
EXPOSE 3000

# Запускаем приложение в режиме разработки
CMD ["bun", "run", "start:dev"]