FROM oven/bun:alpine

RUN apk add --no-cache libc6-compat libstdc++

RUN adduser -D -s /bin/sh -u 1001 nestjsuser

WORKDIR /backend.nestjs

RUN chown nestjsuser:nestjsuser /backend.nestjs

USER nestjsuser

COPY --chown=nestjsuser:nestjsuser package.json bun.lock* ./

RUN bun install

COPY --chown=nestjsuser:nestjsuser . .

EXPOSE 3000

CMD ["bun", "run", "start:dev"]